### ISSUE TITLE
boxplot with wrong argument

### ISSUE THREAD

**Issue by zoonoo** [PacktPublishing/Building-Recommendation-Engines#1]
https://github.com/PacktPublishing/Building-Recommendation-Engines/blob/57839adab7e69677299a9ef19b9bc6cc04a5e956/Chapter%205/chp5_scripts.txt#L66

```
Error in sort.int(x, na.last = na.last, decreasing = decreasing, ...) : 
  'x' must be atomic
In addition: Warning messages:
1: In is.na(x) : is.na() applied to non-(list or vector) of type 'S4'
2: In is.na(x) : is.na() applied to non-(list or vector) of type 'S4'
```

I believe it must be 

`boxplot(rowMeans(model_data))`

**Comment by sarvesh-packt** [comment]
Please reopen if the issue still persists.
